[theme]
primaryColor="#1E3A8A"
backgroundColor="#FAFAFC"
secondaryBackgroundColor="#E6E6E6"
textColor="#1F2937"
font="serif"

[server]
port = 8501
address = "0.0.0.0"
headless = true
enableCORS = true
enableXsrfProtection = true

[browser]
gatherUsageStats = false

[runner]
magicEnabled = true
fastReturns = true
